name: Sync with template

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CUSTOM_GITHUB_PAT }}
          
      - name: Template Sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_repo_path: saicaca/fuwari
          github_token: ${{ secrets.CUSTOM_GITHUB_PAT }}
